export default Object.freeze({
    RED: 'RED',
    YELLOW: 'YELLOW',
    BLUE: 'BLUE',
    GREEN: 'GREEN',
    MIDDLEBROWN: 'MIDDLEBROWN',
    LIGHTBROWN: 'LIGHTBROWN',
    DARKBROWN: 'DARKBROWN',
    PURPLE: 'PURPLE',
    REDBROWN: 'REDBROWN',
    SANDYBROWN: 'SANDYBROWN',
    BLANCHEDALMOND: 'BLANCHEDALMOND',
});
